#!/usr/bin/env python3
"""
=============================================================================
EXECUTION BACKTEST  (prob >= 0.65 watchlist + ORB trigger + SL/TP grid)
=============================================================================

WHAT THIS DOES
--------------
For each watchlist signal (model prob >= PROB_THRESHOLD on day T):
  1. Wait T+1..T+MAX_WATCH_DAYS for the first ORB break (multiple variants).
  2. On break, ENTER at the break-bar 5-min close.
  3. Simulate exit under every (SL, TP) combination from entry forward.
  4. Track MAE/MFE on the full hold path (not just to exit).

ORB VARIANTS (free to add more in ORB_VARIANTS):
  ORB_15m       : 5-min close > first-15-min HIGH
  ORB_30m       : 5-min close > first-30-min HIGH
  ORB_60m       : 5-min close > first-60-min HIGH
  ORB_15m_vwap  : ORB_15m AND break-bar close > session VWAP
  ORB_15m_vol   : ORB_15m AND break-bar volume > 1.5x first-15-min avg volume

EXIT GRID (per trade we compute every combination):
  SL: None, -2%, -3%, -5%, orb_low
  TP: None, +2%, +3%, +5%

GAP-AWARE STOPS:
  At each post-entry bar:
    - SL check first (if low <= SL: fill at min(open, SL); handles gap-down)
    - TP check second (if high >= TP: fill at max(open, TP); handles gap-up)
    - If neither: continue
  After MAX_HOLD_BARS bars (~5 trading days): time-stop at last close.

OUTPUTS (in OUT_DIR):
  01_per_trade.csv             every (signal x variant x SL x TP) row
  02_signal_funnel.csv         watchlist -> break -> entry counts per variant
  03_summary_by_variant.csv    headline stats per ORB variant
  04_by_variant_regime.csv     ORB x regime
  05_by_variant_bucket.csv     ORB x prob bucket
  06_sl_tp_grid_<variant>.csv  full SL x TP heatmap (one per variant)
  07_mae_mfe_distribution.csv  per-variant MAE/MFE percentiles
  08_holding_time_dist.csv     bars-held distribution per variant

ASSUMPTIONS
-----------
* 5-min intraday bars cached as `<symbol>_5min.parquet` per symbol (or per
  symbol+date — set INTRADAY_LAYOUT). Adjust load_intraday_5min() if your
  cache layout differs.
* NSE 9:15-15:30 = 75 5-min bars/day. Holidays skipped automatically by
  joining on actual bar timestamps.
* Watchlist is generated by scoring panel_cache.parquet with the live model
  (m5_ensemble.joblib by default; override via MODEL_FILE).
* Cost: 25 bps round-trip applied to net returns columns.

Run:  python execution_backtest.py
=============================================================================
"""

from __future__ import annotations
import os, sys, json, glob, time, warnings
from pathlib import Path
from typing import List, Dict, Optional, Tuple
import numpy as np
import pandas as pd
from joblib import load

warnings.filterwarnings("ignore")

# =============================================================================
# CONFIG
# =============================================================================
BASE_DIR = Path(r"C:\Users\karanvsi\Desktop\Kite Connect\v3_2_output_full")

# Intraday 5-min bars location. Two layouts supported:
#   INTRADAY_LAYOUT = "per_symbol"      ->  <INTRADAY_DIR>/<SYMBOL>_5min.parquet
#   INTRADAY_LAYOUT = "per_symbol_date" ->  <INTRADAY_DIR>/<SYMBOL>/<YYYY-MM-DD>.parquet
INTRADAY_DIR = Path(r"C:\Users\karanvsi\Desktop\Pycharm\Cache\cache_intraday_5min")
INTRADAY_LAYOUT = "per_symbol"

# Output
OUT_DIR = BASE_DIR / "execution_backtest"
OUT_DIR.mkdir(parents=True, exist_ok=True)

# Watchlist construction
PANEL_PATH    = BASE_DIR / "panel_cache.parquet"
SCHEMA_PATH   = BASE_DIR / "features_train.json"
MODEL_FILE    = BASE_DIR / "models" / "m5_ensemble.joblib"   # pooled fallback
ROUTER_FILE   = BASE_DIR / "models" / "m5_regime_router.joblib"  # optional
USE_REGIME_ROUTER = False    # True = use regime router; False = pooled ensemble
PROB_THRESHOLD    = 0.65
WATCHLIST_OOS_FRACTION = 0.20  # only backtest the last X% of dates (avoid in-sample)
MIN_CLOSE     = 2.0
MIN_AVG20_VOL = 200_000

# ORB / execution
MAX_WATCH_DAYS = 5         # T+1..T+5 to look for the break
MAX_HOLD_DAYS  = 5         # bars from entry to time-stop (in trading days)
BARS_PER_DAY   = 75        # NSE 9:15-15:30 in 5-min bars
MAX_HOLD_BARS  = MAX_HOLD_DAYS * BARS_PER_DAY
ROUND_TRIP_BPS = 25        # 0.25% round-trip cost for net columns
PROB_BUCKETS   = [(0.65, 0.70), (0.70, 0.75), (0.75, 0.80), (0.80, 1.001)]

# ORB variant definitions. Add more here.
ORB_VARIANTS = [
    {"name": "ORB_15m",      "window_min": 15, "filters": []},
    {"name": "ORB_30m",      "window_min": 30, "filters": []},
    {"name": "ORB_60m",      "window_min": 60, "filters": []},
    {"name": "ORB_15m_vwap", "window_min": 15, "filters": ["vwap"]},
    {"name": "ORB_15m_vol",  "window_min": 15, "filters": ["vol_1p5x"]},
]

# Exit grid
SL_OPTIONS = [None, 2.0, 3.0, 5.0, "orb_low"]   # None means no SL
TP_OPTIONS = [None, 2.0, 3.0, 5.0]              # None means no TP


# =============================================================================
# HELPERS
# =============================================================================

def bucket_label(p: float) -> str:
    for lo, hi in PROB_BUCKETS:
        if lo <= p < hi:
            return f"[{lo:.2f}, {hi:.2f})"
    return "out_of_range"


def safe_div(a, b):
    return a / b if b not in (0, None) and not (isinstance(b, float) and np.isnan(b)) else np.nan


def _model_predict_proba(model, X: pd.DataFrame) -> np.ndarray:
    if hasattr(model, "predict_proba"):
        return model.predict_proba(X)[:, 1]
    if hasattr(model, "members") and model.members:
        ps = [m.predict_proba(X)[:, 1] for m in model.members]
        return np.mean(ps, axis=0)
    raise RuntimeError("Cannot score with this model object.")


def load_watchlist() -> pd.DataFrame:
    """Score panel with the live model. Return rows with prob >= PROB_THRESHOLD,
    restricted to the OOS slice (last WATCHLIST_OOS_FRACTION of dates).
    Columns: symbol, date, prob, regime."""
    print(f"[Load] Panel: {PANEL_PATH}")
    panel = pd.read_parquet(PANEL_PATH)
    panel["timestamp"] = pd.to_datetime(panel["timestamp"])
    if panel["timestamp"].dt.tz is not None:
        panel["timestamp"] = panel["timestamp"].dt.tz_convert("Asia/Kolkata")
    panel["date"] = panel["timestamp"].dt.normalize()

    # Universe filter
    panel["avg20_vol"] = panel.groupby("symbol")["volume"].transform(
        lambda s: s.rolling(20, min_periods=1).mean())
    universe = (panel["close"] >= MIN_CLOSE) & (panel["avg20_vol"] >= MIN_AVG20_VOL)
    panel = panel[universe].reset_index(drop=True)

    # OOS slice
    all_dates = np.sort(panel["date"].unique())
    cut_idx = int(len(all_dates) * (1 - WATCHLIST_OOS_FRACTION))
    test_start = pd.Timestamp(all_dates[cut_idx])
    print(f"[Load] OOS test window: {test_start.date()} to {pd.Timestamp(all_dates[-1]).date()}")
    panel_test = panel[panel["date"] >= test_start].copy()

    # Schema + model
    schema = json.loads(SCHEMA_PATH.read_text())
    feats = list(schema["features"])
    impute = {k: float(v) for k, v in schema["impute"].items()}
    X = panel_test.reindex(columns=feats).copy()
    for c in feats:
        X[c] = pd.to_numeric(X[c], errors="coerce").fillna(impute.get(c, 0.0))

    if USE_REGIME_ROUTER and ROUTER_FILE.exists():
        print(f"[Load] Router: {ROUTER_FILE}")
        router = load(ROUTER_FILE)
        regime_vec = panel_test["stock_regime"].fillna("bull_trend").reset_index(drop=True)
        prob = router.predict_proba_by_regime(X.reset_index(drop=True), regime_vec)
    else:
        print(f"[Load] Pooled model: {MODEL_FILE}")
        model = load(MODEL_FILE)
        prob = _model_predict_proba(model, X)

    panel_test["prob"] = prob
    wl = panel_test[panel_test["prob"] >= PROB_THRESHOLD].copy()
    wl["regime"] = wl.get("stock_regime", "unknown").fillna("unknown")
    wl = wl[["symbol", "date", "prob", "regime"]].reset_index(drop=True)
    print(f"[Watchlist] {len(wl):,} signals at prob >= {PROB_THRESHOLD} "
          f"(out of {len(panel_test):,} panel rows in OOS window)")
    return wl


def load_intraday_5min(symbol: str, day: pd.Timestamp) -> Optional[pd.DataFrame]:
    """Load 5-min bars for symbol on `day` (one trading day).
    Returns DataFrame[timestamp(IST tz-aware), open, high, low, close, volume]
    sorted ascending. Returns None if file missing / empty / no bars on this day."""
    day_norm = day.normalize().tz_localize(None) if hasattr(day, "tz_localize") and day.tz is None else day.normalize()
    if hasattr(day_norm, "tz") and day_norm.tz is not None:
        day_norm = day_norm.tz_localize(None)

    if INTRADAY_LAYOUT == "per_symbol":
        path = INTRADAY_DIR / f"{symbol}_5min.parquet"
        if not path.exists():
            # try without _5min suffix
            alt = INTRADAY_DIR / f"{symbol}.parquet"
            if alt.exists():
                path = alt
            else:
                return None
        try:
            df = pd.read_parquet(path)
        except Exception:
            return None
    elif INTRADAY_LAYOUT == "per_symbol_date":
        path = INTRADAY_DIR / symbol / f"{day_norm.strftime('%Y-%m-%d')}.parquet"
        if not path.exists():
            return None
        try:
            df = pd.read_parquet(path)
        except Exception:
            return None
    else:
        raise ValueError(f"Unknown INTRADAY_LAYOUT: {INTRADAY_LAYOUT}")

    if df is None or df.empty:
        return None

    # Normalize columns
    cmap = {c.lower(): c for c in df.columns}
    ts_col = cmap.get("timestamp") or cmap.get("date") or cmap.get("datetime")
    if ts_col is None:
        return None
    df["timestamp"] = pd.to_datetime(df[ts_col])
    if df["timestamp"].dt.tz is None:
        df["timestamp"] = df["timestamp"].dt.tz_localize("Asia/Kolkata", nonexistent="shift_forward",
                                                         ambiguous="NaT")
    else:
        df["timestamp"] = df["timestamp"].dt.tz_convert("Asia/Kolkata")
    df = df.dropna(subset=["timestamp"]).sort_values("timestamp").reset_index(drop=True)

    # Lowercase OHLCV
    for src, dst in (("Open", "open"), ("High", "high"), ("Low", "low"),
                     ("Close", "close"), ("Volume", "volume")):
        if src in df.columns and dst not in df.columns:
            df[dst] = df[src]
    needed = ["timestamp", "open", "high", "low", "close", "volume"]
    if not all(c in df.columns for c in needed):
        return None
    df = df[needed].copy()
    for c in ("open", "high", "low", "close", "volume"):
        df[c] = pd.to_numeric(df[c], errors="coerce")
    df = df.dropna(subset=["open", "high", "low", "close"]).reset_index(drop=True)

    # Slice to the requested day (IST date)
    same_day = df["timestamp"].dt.normalize() == pd.Timestamp(day_norm).tz_localize("Asia/Kolkata")
    df_day = df.loc[same_day].reset_index(drop=True)
    if df_day.empty:
        return None
    return df_day


def compute_orb_levels(bars: pd.DataFrame, window_min: int) -> Optional[Tuple[float, float, int]]:
    """Compute opening-range high/low over the first `window_min` minutes.
    Returns (orb_high, orb_low, last_orb_bar_idx) or None."""
    n_bars = max(1, window_min // 5)
    if len(bars) < n_bars + 1:
        return None
    orb_slice = bars.iloc[:n_bars]
    orb_high = float(orb_slice["high"].max())
    orb_low  = float(orb_slice["low"].min())
    last_idx = n_bars - 1
    return orb_high, orb_low, last_idx


def find_orb_break(bars: pd.DataFrame, orb_high: float, orb_low: float,
                   start_idx: int, variant: dict) -> Optional[Dict]:
    """Find the first 5-min bar (idx >= start_idx) whose CLOSE > orb_high
    AND any variant-specific filter passes.
    Returns {idx, time, close, vwap_at_break, vol_at_break} or None."""
    if start_idx >= len(bars):
        return None

    # Pre-compute session VWAP up to each bar (cumulative typical-price-weighted)
    typical = (bars["high"] + bars["low"] + bars["close"]) / 3.0
    cum_pv = (typical * bars["volume"]).cumsum()
    cum_v  = bars["volume"].cumsum().replace(0, np.nan)
    vwap_series = cum_pv / cum_v

    n_orb_bars = (start_idx + 1)
    orb_avg_vol = bars.iloc[:n_orb_bars]["volume"].mean() if n_orb_bars > 0 else 0.0

    for i in range(start_idx, len(bars)):
        row = bars.iloc[i]
        close = float(row["close"])
        if close <= orb_high:
            continue

        # Filters
        ok = True
        for f in variant.get("filters", []):
            if f == "vwap":
                vwap_now = float(vwap_series.iloc[i]) if pd.notna(vwap_series.iloc[i]) else None
                if vwap_now is None or close <= vwap_now:
                    ok = False
                    break
            elif f == "vol_1p5x":
                vol_now = float(row["volume"])
                if orb_avg_vol == 0 or vol_now < 1.5 * orb_avg_vol:
                    ok = False
                    break
        if not ok:
            continue

        return {
            "idx": int(i),
            "time": row["timestamp"],
            "close": close,
            "vwap_at_break": float(vwap_series.iloc[i]) if pd.notna(vwap_series.iloc[i]) else np.nan,
            "vol_at_break": float(row["volume"]),
        }
    return None


def collect_post_entry_bars(symbol: str, entry_day: pd.Timestamp, entry_idx_in_day: int,
                            max_bars: int) -> Optional[pd.DataFrame]:
    """Concatenate 5-min bars from entry_idx_in_day on entry_day forward,
    spanning subsequent trading days, up to max_bars bars."""
    out = []
    same_day = load_intraday_5min(symbol, entry_day)
    if same_day is None:
        return None
    out.append(same_day.iloc[entry_idx_in_day:].reset_index(drop=True))

    days_forward = 1
    while sum(len(x) for x in out) < max_bars and days_forward <= MAX_HOLD_DAYS + 7:
        next_day = entry_day + pd.Timedelta(days=days_forward)
        days_forward += 1
        # Skip weekends
        if next_day.weekday() >= 5:
            continue
        nxt = load_intraday_5min(symbol, next_day)
        if nxt is None:
            continue  # holiday / missing
        out.append(nxt)

    if not out:
        return None
    full = pd.concat(out, ignore_index=True).reset_index(drop=True)
    return full.iloc[:max_bars].reset_index(drop=True)


def derive_exit(entry_price: float, post_bars: pd.DataFrame,
                sl_price: Optional[float], tp_price: Optional[float]) -> Dict:
    """Walk forward through post_bars (excluding the entry bar itself if you've
    already sliced; here post_bars[0] is the bar AFTER entry). Apply gap-aware
    stop-before-target logic. If neither hits, time-stop at last bar's close.

    Returns dict: exit_price, exit_reason, bars_held, return_pct, mae_pct, mfe_pct.
    """
    if post_bars is None or len(post_bars) == 0:
        return {
            "exit_price": entry_price, "exit_reason": "no_data",
            "bars_held": 0, "return_pct": 0.0, "mae_pct": 0.0, "mfe_pct": 0.0,
        }

    mae_low  = entry_price
    mfe_high = entry_price

    for i, row in enumerate(post_bars.itertuples(index=False)):
        bar_open  = float(row.open)
        bar_high  = float(row.high)
        bar_low   = float(row.low)
        bar_close = float(row.close)

        mae_low  = min(mae_low, bar_low)
        mfe_high = max(mfe_high, bar_high)

        # SL FIRST (gap-down: if open <= sl, fill at open; else fill at sl)
        if sl_price is not None and bar_low <= sl_price:
            fill = bar_open if bar_open <= sl_price else sl_price
            return {
                "exit_price": fill, "exit_reason": "sl",
                "bars_held": i + 1,
                "return_pct": (fill / entry_price - 1) * 100,
                "mae_pct": (mae_low / entry_price - 1) * 100,
                "mfe_pct": (mfe_high / entry_price - 1) * 100,
            }

        # TP SECOND (gap-up: if open >= tp, fill at open; else at tp)
        if tp_price is not None and bar_high >= tp_price:
            fill = bar_open if bar_open >= tp_price else tp_price
            return {
                "exit_price": fill, "exit_reason": "tp",
                "bars_held": i + 1,
                "return_pct": (fill / entry_price - 1) * 100,
                "mae_pct": (mae_low / entry_price - 1) * 100,
                "mfe_pct": (mfe_high / entry_price - 1) * 100,
            }

    # Time stop at last bar close
    last_close = float(post_bars.iloc[-1]["close"])
    return {
        "exit_price": last_close, "exit_reason": "time",
        "bars_held": len(post_bars),
        "return_pct": (last_close / entry_price - 1) * 100,
        "mae_pct": (mae_low / entry_price - 1) * 100,
        "mfe_pct": (mfe_high / entry_price - 1) * 100,
    }


def compute_sl_price(entry_price: float, sl_opt, orb_low: float) -> Optional[float]:
    if sl_opt is None:
        return None
    if isinstance(sl_opt, str) and sl_opt == "orb_low":
        return orb_low
    return entry_price * (1 - float(sl_opt) / 100.0)


# =============================================================================
# MAIN BACKTEST
# =============================================================================

def run_backtest():
    t0 = time.perf_counter()
    watchlist = load_watchlist()
    if watchlist.empty:
        print("[ERROR] Empty watchlist; nothing to backtest.")
        return None

    rows = []
    funnel = []
    cost_pct = ROUND_TRIP_BPS / 100.0  # e.g. 25 bps -> 0.25%

    n_signals = len(watchlist)
    for s_idx, sig in watchlist.iterrows():
        T = pd.Timestamp(sig["date"]).tz_localize(None) if pd.Timestamp(sig["date"]).tz is None \
            else pd.Timestamp(sig["date"]).tz_convert("Asia/Kolkata").tz_localize(None)
        symbol = sig["symbol"]
        prob = float(sig["prob"])
        regime = sig["regime"]

        if (s_idx + 1) % 500 == 0:
            print(f"[Backtest] {s_idx+1:,}/{n_signals:,} signals processed "
                  f"(elapsed {time.perf_counter()-t0:.0f}s)")

        for variant in ORB_VARIANTS:
            broken = False
            for d_off in range(1, MAX_WATCH_DAYS + 1):
                wd = T + pd.Timedelta(days=d_off)
                if wd.weekday() >= 5:
                    continue
                bars = load_intraday_5min(symbol, wd)
                if bars is None or len(bars) < (variant["window_min"] // 5) + 1:
                    continue

                lvl = compute_orb_levels(bars, variant["window_min"])
                if lvl is None:
                    continue
                orb_high, orb_low, last_orb_idx = lvl

                brk = find_orb_break(bars, orb_high, orb_low, last_orb_idx + 1, variant)
                if brk is None:
                    continue

                # ENTRY at break-bar close
                entry_price = brk["close"]
                entry_idx = brk["idx"]
                # Bars AFTER entry (entry bar excluded -- realistic: stop/target test starts next bar)
                post_bars = collect_post_entry_bars(symbol, wd, entry_idx + 1, MAX_HOLD_BARS)
                if post_bars is None or len(post_bars) == 0:
                    continue

                # MAE/MFE on FULL hold path (no SL/TP) -- diagnostic
                lows_min = float(post_bars["low"].min())
                highs_max = float(post_bars["high"].max())
                mae_full = (lows_min / entry_price - 1) * 100
                mfe_full = (highs_max / entry_price - 1) * 100

                funnel.append({
                    "variant": variant["name"], "symbol": symbol, "signal_date": T,
                    "entry_date": wd, "days_to_break": d_off,
                    "orb_high": orb_high, "orb_low": orb_low,
                    "entry_price": entry_price,
                    "mae_full_pct": mae_full, "mfe_full_pct": mfe_full,
                    "prob": prob, "regime": regime,
                    "prob_bucket": bucket_label(prob),
                })

                # Exit grid: every (sl, tp) combination
                for sl_opt in SL_OPTIONS:
                    sl_price = compute_sl_price(entry_price, sl_opt, orb_low)
                    for tp_opt in TP_OPTIONS:
                        tp_price = entry_price * (1 + float(tp_opt) / 100.0) if tp_opt is not None else None
                        ex = derive_exit(entry_price, post_bars, sl_price, tp_price)
                        rows.append({
                            "symbol": symbol, "signal_date": T,
                            "entry_date": wd, "days_to_break": d_off,
                            "variant": variant["name"],
                            "orb_high": orb_high, "orb_low": orb_low,
                            "entry_price": entry_price,
                            "sl_opt": str(sl_opt), "tp_opt": str(tp_opt) if tp_opt is not None else "None",
                            "sl_price": sl_price, "tp_price": tp_price,
                            "exit_price": ex["exit_price"],
                            "exit_reason": ex["exit_reason"],
                            "bars_held": ex["bars_held"],
                            "return_pct": ex["return_pct"],
                            "net_return_pct": ex["return_pct"] - cost_pct,
                            "mae_pct": ex["mae_pct"],
                            "mfe_pct": ex["mfe_pct"],
                            "mae_full_pct": mae_full,
                            "mfe_full_pct": mfe_full,
                            "prob": prob, "regime": regime,
                            "prob_bucket": bucket_label(prob),
                        })
                broken = True
                break  # this variant got its break -- next variant
            # End of watch-day loop. If broken==False, no entry recorded for this variant.

    df = pd.DataFrame(rows)
    funnel_df = pd.DataFrame(funnel)
    elapsed = time.perf_counter() - t0
    print(f"[Backtest] Done in {elapsed:.0f}s. Total trade-rows: {len(df):,}  "
          f"unique entries: {len(funnel_df):,}")
    return df, funnel_df, watchlist


# =============================================================================
# AGGREGATIONS
# =============================================================================

def _agg_block(df: pd.DataFrame) -> pd.Series:
    n = len(df)
    if n == 0:
        return pd.Series({"n": 0})
    return pd.Series({
        "n": n,
        "win_rate_pct": (df["return_pct"] > 0).mean() * 100,
        "avg_ret_pct": df["return_pct"].mean(),
        "median_ret_pct": df["return_pct"].median(),
        "std_pct": df["return_pct"].std(),
        "avg_net_pct": df["net_return_pct"].mean(),
        "sharpe_per_trade": (df["return_pct"].mean() / df["return_pct"].std()
                              if df["return_pct"].std() > 0 else np.nan),
        "tp_rate_pct": (df["exit_reason"] == "tp").mean() * 100,
        "sl_rate_pct": (df["exit_reason"] == "sl").mean() * 100,
        "time_rate_pct": (df["exit_reason"] == "time").mean() * 100,
        "avg_bars_held": df["bars_held"].mean(),
        "avg_mae_pct": df["mae_pct"].mean(),
        "avg_mfe_pct": df["mfe_pct"].mean(),
        "p10_ret": df["return_pct"].quantile(0.10),
        "p90_ret": df["return_pct"].quantile(0.90),
    })


def write_summaries(df: pd.DataFrame, funnel_df: pd.DataFrame, watchlist: pd.DataFrame):
    # 02 funnel: how many signals -> entries per variant
    sig_count = len(watchlist)
    funnel_summary = (funnel_df.groupby("variant")
                      .size().rename("n_entries").reset_index())
    funnel_summary["n_signals"] = sig_count
    funnel_summary["entry_rate_pct"] = (funnel_summary["n_entries"] / sig_count * 100).round(2)
    # days-to-break percentiles per variant
    dtb = (funnel_df.groupby("variant")["days_to_break"]
           .agg(["mean", "median", "max"]).reset_index()
           .rename(columns={"mean": "days_to_break_avg",
                            "median": "days_to_break_median",
                            "max": "days_to_break_max"}))
    funnel_summary = funnel_summary.merge(dtb, on="variant", how="left")
    funnel_summary.to_csv(OUT_DIR / "02_signal_funnel.csv", index=False)
    print(f"[Out] 02_signal_funnel.csv -> {len(funnel_summary)} variants")

    # 03 by variant (use the "no SL, no TP" cells -- pure ORB hold)
    pure = df[(df["sl_opt"] == "None") & (df["tp_opt"] == "None")]
    by_var = pure.groupby("variant").apply(_agg_block).reset_index()
    by_var.to_csv(OUT_DIR / "03_summary_by_variant.csv", index=False)
    print(f"[Out] 03_summary_by_variant.csv -> {len(by_var)} variants")

    # 04 by variant x regime
    by_vr = pure.groupby(["variant", "regime"]).apply(_agg_block).reset_index()
    by_vr.to_csv(OUT_DIR / "04_by_variant_regime.csv", index=False)
    print(f"[Out] 04_by_variant_regime.csv -> {len(by_vr)} cells")

    # 05 by variant x prob bucket
    by_vb = pure.groupby(["variant", "prob_bucket"]).apply(_agg_block).reset_index()
    by_vb.to_csv(OUT_DIR / "05_by_variant_bucket.csv", index=False)
    print(f"[Out] 05_by_variant_bucket.csv -> {len(by_vb)} cells")

    # 06 SL x TP grid per variant
    for variant in df["variant"].unique():
        sub = df[df["variant"] == variant]
        grid = sub.groupby(["sl_opt", "tp_opt"]).apply(_agg_block).reset_index()
        grid.to_csv(OUT_DIR / f"06_sl_tp_grid_{variant}.csv", index=False)
        print(f"[Out] 06_sl_tp_grid_{variant}.csv -> {len(grid)} cells")

    # 07 MAE/MFE distribution per variant (use full-hold path, dedupe per entry)
    if not funnel_df.empty:
        rows = []
        for variant in funnel_df["variant"].unique():
            sub = funnel_df[funnel_df["variant"] == variant]
            for q in (0.05, 0.10, 0.25, 0.50, 0.75, 0.90, 0.95):
                rows.append({
                    "variant": variant, "quantile": q,
                    "mae_pct_q": sub["mae_full_pct"].quantile(q),
                    "mfe_pct_q": sub["mfe_full_pct"].quantile(q),
                })
        pd.DataFrame(rows).to_csv(OUT_DIR / "07_mae_mfe_distribution.csv", index=False)
        print(f"[Out] 07_mae_mfe_distribution.csv")

    # 08 holding time distribution
    rows = []
    for variant in pure["variant"].unique():
        sub = pure[pure["variant"] == variant]
        for q in (0.10, 0.25, 0.50, 0.75, 0.90):
            rows.append({
                "variant": variant, "quantile": q,
                "bars_held_q": sub["bars_held"].quantile(q),
                "approx_days": sub["bars_held"].quantile(q) / BARS_PER_DAY,
            })
    pd.DataFrame(rows).to_csv(OUT_DIR / "08_holding_time_dist.csv", index=False)
    print(f"[Out] 08_holding_time_dist.csv")


# =============================================================================
# ENTRY POINT
# =============================================================================

def main():
    print("=" * 70)
    print("EXECUTION BACKTEST")
    print(f"  PROB_THRESHOLD     = {PROB_THRESHOLD}")
    print(f"  MAX_WATCH_DAYS     = {MAX_WATCH_DAYS}")
    print(f"  MAX_HOLD_BARS      = {MAX_HOLD_BARS}  (~{MAX_HOLD_DAYS} trading days)")
    print(f"  ORB_VARIANTS       = {[v['name'] for v in ORB_VARIANTS]}")
    print(f"  SL_OPTIONS         = {SL_OPTIONS}")
    print(f"  TP_OPTIONS         = {TP_OPTIONS}")
    print(f"  ROUND_TRIP_BPS     = {ROUND_TRIP_BPS}")
    print("=" * 70)

    out = run_backtest()
    if out is None:
        return
    df, funnel_df, watchlist = out

    # 01 per-trade
    df.to_csv(OUT_DIR / "01_per_trade.csv", index=False)
    print(f"[Out] 01_per_trade.csv -> {len(df):,} rows")

    write_summaries(df, funnel_df, watchlist)
    print(f"\n[Done] All outputs written to: {OUT_DIR}")


if __name__ == "__main__":
    main()
